// AUTO-GENERATED by better-intl. Do not edit by hand.
// Regenerated automatically by the Next.js plugin on dev/build.

/* eslint-disable */
import { createI18n } from "better-intl/runtime";

export const translations = {
	pt: {
		app: {
			blog: {
				title: "blog",
				intro: "posts gerados automaticamente a partir dos meus repositórios públicos.",
				empty: "nenhum post ainda. assim que eu publicar um repositório com o tópico portfolio, ele aparece aqui.",
				back: "← voltar pro blog",
				repo: "ver repositório",
				live: "ver no ar",
				stars: (v: { count: string }) => `${v.count} estrelas`,
				onlyPt: "este post só está disponível em português.",
				noReadme: "esse repositório ainda não tem README.",
			},
			cv: {
				title: "currículo",
				description: "Currículo do Cauã Diorio, desenvolvedor front-end.",
				print: "salvar em PDF",
				summary: "resumo",
				openSource: "open source",
			},
			lab: {
				title: "lab",
				intro: "experimentos de interface: detalhes de interação pequenos, feitos pra sentir na mão. tudo aqui é código de verdade rodando no seu navegador.",
				hold: {
					title: "segurar pra confirmar",
					desc: "ação destrutiva pede intenção: o preenchimento leva 1,6 s enquanto você segura e volta em 200 ms quando solta. funciona com espaço ou enter também.",
					label: "segure pra apagar",
					done: "apagado",
				},
				copy: {
					title: "copiar com troca de ícone",
					desc: "o ícone troca com um leve desfoque, que junta os dois estados num movimento só em vez de dois ícones se sobrepondo.",
					label: "copiar",
					done: "copiado",
				},
				tabs: {
					title: "abas com recorte",
					desc: "uma cópia da lista em cor invertida fica por cima, recortada só na aba ativa. a cor troca sem nenhuma aba piscar no meio do caminho.",
					label: "período",
					day: "hoje",
					week: "semana",
					month: "mês",
					year: "ano",
				},
				terminal: {
					title: "terminal",
					desc: "navegue pelo site por comandos. sem animação de propósito: o que é feito no teclado precisa ser instantâneo.",
					label: "comando",
					placeholder: "digite help",
					help: "comandos: help, whoami, ls, cd <lugar>, date, echo <texto>, clear",
					whoami: "cauã · desenvolvedor front-end · jaú, sp",
					sudo: "boa tentativa.",
					notFound: (v: { cmd: string }) => `comando não encontrado: ${v.cmd}`,
					noDir: (v: { dir: string }) => `cd: ${v.dir}: diretório inexistente`,
				},
				sheet: {
					title: "gaveta com arraste",
					desc: "arraste pra baixo pra fechar. um peteleco rápido fecha mesmo com pouca distância (velocidade > 0,11 px/ms); puxar pra cima resiste, em vez de bater numa parede.",
					open: "abrir gaveta",
					sheetTitle: "filtros",
					body: "a gaveta segue o dedo 1:1 e volta com a curva de gaveta do iOS.",
					close: "Fechar gaveta",
					hint: "arraste pela gaveta ou aperte Esc.",
				},
				reorder: {
					title: "lista com FLIP",
					desc: "o layout muda de uma vez; o transform anima a diferença de posição (First, Last, Invert, Play) em 250ms. nada de animar top ou altura.",
					label: "Tarefas",
					item1: "revisar o PR",
					item2: "escrever os testes",
					item3: "ajustar o motion",
					item4: "fazer o deploy",
					up: "Subir",
					down: "Descer",
					shuffle: "embaralhar",
				},
				compare: {
					title: "antes e depois",
					desc: "o mesmo card duas vezes, o de cima recortado por clip-path. arraste a alça ou use as setas (shift anda mais).",
					label: "Comparar antes e depois",
					before: "antes",
					after: "depois",
					cardTitle: "relatório mensal",
					cardMeta: "atualizado há 2 horas",
					cardAction: "abrir",
				},
			},
			meta: {
				title: "Cauã Diorio · desenvolvedor front-end",
				description: "Desenvolvedor front-end. Interface, interação e os detalhes que fazem um produto ser bom de usar.",
			},
			role: "desenvolvedor front-end júnior",
			bubble: "e aí!",
			today: "hoje",
			bio: "front-end júnior na loopscape, no loopvet e na domus. gosto da parte que as pessoas tocam: interface, interação e detalhe.",
			ai: "uso IA em quase todo projeto pra aprender mais rápido, sem pular o porquê.",
			projects: {
				title: "projetos",
				loopvet: "gestão pra clínica veterinária.",
				domus: "CMS que virou plataforma de conteúdo.",
				cdui: "minha biblioteca de componentes, medida em bytes.",
				converter: "conversores de arquivo que rodam no navegador. nada sai do seu computador.",
				cdai: "agente de código com IA que roda local, com Ollama, Tauri e Rust.",
				atWork: "na loopscape",
				soon: "em breve",
				all: "todos os repositórios",
				contributions: (v: { count: string }) => `${v.count} contribuições no último ano`,
			},
			stack: {
				title: "stack",
			},
			error: {
				title: "algo deu errado.",
				body: "provavelmente a API do GitHub não respondeu. tenta de novo daqui a pouco.",
				retry: "tentar de novo",
			},
			repos: {
				title: "em destaque no github",
				all: "ver todos →",
				stars: (v: { count: string }) => `${v.count} estrelas`,
				open: "ver",
				openLabel: (v: { name: string }) => `ver ${v.name}`,
			},
			writing: {
				title: "escrita",
				all: "ver todos →",
			},
			notFound: {
				path: "pagina-que-nao-existe",
				error: "cd: arquivo ou diretório inexistente",
				title: "essa página não existe.",
				body: "o link pode estar quebrado ou a página mudou de lugar. digita cd .. ou volta pelo link abaixo.",
				home: "voltar pro começo",
			},
			experience: {
				title: "experiência",
				current: "atual",
				role: "desenvolvedor front-end júnior",
			},
		},
		components: {
			"site-shell": {
				nav: {
					label: "Navegação",
					home: "início",
					blog: "blog",
					lab: "lab",
					experience: "experiência",
					projects: "projetos",
					email: "e-mail",
					cv: "CV",
				},
				theme: {
					toLight: "Mudar pro tema claro",
					toDark: "Mudar pro tema escuro",
				},
				language: {
					label: "Idioma",
				},
				footer: {
					made: "feito por cauã.",
					hint: "psst: digita",
					social: "Redes",
				},
			},
		},
	},
	en: {
		app: {
			blog: {
				title: "blog",
				intro: "posts generated automatically from my public repositories.",
				empty: "no posts yet. as soon as i publish a repository tagged portfolio, it shows up here.",
				back: "← back to blog",
				repo: "view repository",
				live: "see it live",
				stars: (v: { count: string }) => `${v.count} stars`,
				onlyPt: "this post is only available in portuguese.",
				noReadme: "this repository has no README yet.",
			},
			cv: {
				title: "résumé",
				description: "Résumé of Cauã Diorio, front-end developer.",
				print: "save as PDF",
				summary: "summary",
				openSource: "open source",
			},
			lab: {
				title: "lab",
				intro: "interface experiments: small interaction details, made to be felt. everything here is real code running in your browser.",
				hold: {
					title: "hold to confirm",
					desc: "destructive actions need intent: the fill takes 1.6 s while you hold and snaps back in 200 ms when you let go. space or enter work too.",
					label: "hold to delete",
					done: "deleted",
				},
				copy: {
					title: "copy with icon swap",
					desc: "the icon swaps through a slight blur, blending both states into one motion instead of two icons overlapping.",
					label: "copy",
					done: "copied",
				},
				tabs: {
					title: "clip-path tabs",
					desc: "an inverted copy of the list sits on top, clipped to the active tab. the color changes without any tab flickering mid-way.",
					label: "period",
					day: "today",
					week: "week",
					month: "month",
					year: "year",
				},
				terminal: {
					title: "terminal",
					desc: "navigate the site with commands. no animation on purpose: keyboard actions should be instant.",
					label: "command",
					placeholder: "type help",
					help: "commands: help, whoami, ls, cd <place>, date, echo <text>, clear",
					whoami: "cauã · front-end developer · jaú, sp",
					sudo: "nice try.",
					notFound: (v: { cmd: string }) => `command not found: ${v.cmd}`,
					noDir: (v: { dir: string }) => `cd: ${v.dir}: no such directory`,
				},
				sheet: {
					title: "draggable sheet",
					desc: "drag down to close. a quick flick closes it even over a short distance (velocity > 0.11 px/ms); pulling up resists instead of hitting a wall.",
					open: "open sheet",
					sheetTitle: "filters",
					body: "the sheet follows your finger 1:1 and settles with the iOS drawer curve.",
					close: "Close sheet",
					hint: "drag the sheet or press Esc.",
				},
				reorder: {
					title: "FLIP reordering",
					desc: "the layout changes at once; a transform animates the position difference (First, Last, Invert, Play) in 250ms. no animating top or height.",
					label: "Tasks",
					item1: "review the PR",
					item2: "write the tests",
					item3: "tune the motion",
					item4: "ship it",
					up: "Move up",
					down: "Move down",
					shuffle: "shuffle",
				},
				compare: {
					title: "before and after",
					desc: "the same card twice, the top one cut by clip-path. drag the handle or use the arrow keys (shift moves further).",
					label: "Compare before and after",
					before: "before",
					after: "after",
					cardTitle: "monthly report",
					cardMeta: "updated 2 hours ago",
					cardAction: "open",
				},
			},
			meta: {
				title: "Cauã Diorio · front-end developer",
				description: "Front-end developer. Interface, interaction and the details that make a product good to use.",
			},
			role: "junior front-end developer",
			bubble: "hey!",
			today: "today",
			bio: "junior front-end at loopscape, on loopvet and domus. i like the part people touch: interface, interaction and detail.",
			ai: "i use AI on almost every project to learn faster, without skipping the why.",
			projects: {
				title: "projects",
				loopvet: "management software for vet clinics.",
				domus: "a CMS that grew into a content platform.",
				cdui: "my component library, measured in bytes.",
				converter: "file converters that run in the browser. nothing leaves your computer.",
				cdai: "a local AI coding agent built with Ollama, Tauri and Rust.",
				atWork: "at loopscape",
				soon: "soon",
				all: "all repositories",
				contributions: (v: { count: string }) => `${v.count} contributions in the last year`,
			},
			stack: {
				title: "stack",
			},
			error: {
				title: "something went wrong.",
				body: "the GitHub API probably didn't respond. try again in a moment.",
				retry: "try again",
			},
			repos: {
				title: "featured on github",
				all: "see all →",
				stars: (v: { count: string }) => `${v.count} stars`,
				open: "view",
				openLabel: (v: { name: string }) => `view ${v.name}`,
			},
			writing: {
				title: "writing",
				all: "see all →",
			},
			notFound: {
				path: "page-that-doesnt-exist",
				error: "cd: no such file or directory",
				title: "this page doesn't exist.",
				body: "the link may be broken or the page moved. type cd .. or head back with the link below.",
				home: "back to the start",
			},
			experience: {
				title: "experience",
				current: "current",
				role: "junior front-end developer",
			},
		},
		components: {
			"site-shell": {
				nav: {
					label: "Navigation",
					home: "home",
					blog: "blog",
					lab: "lab",
					experience: "experience",
					projects: "projects",
					email: "email",
					cv: "CV",
				},
				theme: {
					toLight: "Switch to light theme",
					toDark: "Switch to dark theme",
				},
				language: {
					label: "Language",
				},
				footer: {
					made: "made by cauã.",
					hint: "psst: type",
					social: "Social",
				},
			},
		},
	},
} as const;

export type Locale = keyof typeof translations;

/** Runtime config for `better-intl/runtime`, baked into the helpers below. */
export const intlConfig = {
	"defaultLocale": "pt",
	"locales": [
		"pt",
		"en"
	],
	"storage": {
		"type": "cookie",
		"key": "locale"
	}
} as const;

// Helpers bound to `translations` + `intlConfig` once. Import `t` anywhere
// (sync on both client and server); call `setLocale()` once per request in the
// root layout; `getLocale()` returns the active locale string; call
// `updateLocale(locale)` to persist a new preference.
const i18n = createI18n(translations, intlConfig);
export const { t, setLocale, getLocale, updateLocale } = i18n;
