// AUTO-GENERATED by better-intl. Do not edit by hand.
// Regenerated automatically by the Next.js plugin on dev/build.

/* eslint-disable */
import { createI18n } from "better-intl/runtime";

export const translations = {
	pt: {
		app: {
			blog: {
				title: "blog",
				intro: "posts gerados automaticamente a partir dos meus repositórios públicos.",
				empty: "nenhum post ainda. assim que eu publicar um repositório com o tópico portfolio, ele aparece aqui.",
				back: "← voltar pro blog",
				repo: "ver repositório",
				live: "ver no ar",
				stars: (v: { count: string }) => `${v.count} estrelas`,
				onlyPt: "este post só está disponível em português.",
				noReadme: "esse repositório ainda não tem README.",
			},
			meta: {
				title: "Cauã Diorio · desenvolvedor front-end",
				description: "Desenvolvedor front-end. Interface, interação e os detalhes que fazem um produto ser bom de usar.",
			},
			role: "desenvolvedor front-end",
			bio: "cuido da parte que as pessoas veem e usam: interface, interação e os detalhes que fazem um produto ser bom de usar. hoje trabalho no loopvet, sistema pra clínica veterinária, e no domus, um CMS que virou plataforma de conteúdo.",
			contributions: {
				count: (v: { count: string }) => `${v.count} contribuições no último ano em`,
				fallback: "contribuições no último ano em",
				less: "menos",
				more: "mais",
				day: (v: { count: string; date: string }) => `${v.count} contribuições em ${v.date}`,
			},
			projects: {
				title: "projetos em que eu trabalhei",
				loopvet: "sistema de gestão pra clínica veterinária: agenda, prontuário e financeiro.",
				domus: "CMS que virou plataforma de marketing de conteúdo: artigos, API e links de campanha com métricas.",
				converter: "conversores que pegam dado bagunçado de outro sistema e entregam arrumado no banco.",
			},
			repos: {
				title: "em destaque no github",
				all: "ver todos →",
				stars: (v: { count: string }) => `${v.count} estrelas`,
			},
			writing: {
				title: "escrita",
				all: "ver todos →",
			},
			notFound: {
				path: "pagina-que-nao-existe",
				error: "cd: arquivo ou diretório inexistente",
				title: "essa página não existe.",
				body: "o link pode estar quebrado ou a página mudou de lugar. digita cd .. ou volta pelo link abaixo.",
				home: "voltar pro começo",
			},
			experience: {
				title: "experiência",
				current: "atual",
				role: "desenvolvedor front-end",
			},
		},
		components: {
			"site-shell": {
				tagline: "jaú, sp · brasil",
				nav: {
					label: "Seções e redes",
					blog: "blog",
					experience: "experiência",
					projects: "projetos",
					email: "e-mail",
					cv: "CV",
				},
				theme: {
					toLight: "Mudar pro tema claro",
					toDark: "Mudar pro tema escuro",
				},
				language: {
					label: "Idioma",
				},
				footer: {
					made: "feito por cauã.",
					hint: "psst: digita",
				},
			},
		},
	},
	en: {
		app: {
			blog: {
				title: "blog",
				intro: "posts generated automatically from my public repositories.",
				empty: "no posts yet. as soon as i publish a repository tagged portfolio, it shows up here.",
				back: "← back to blog",
				repo: "view repository",
				live: "see it live",
				stars: (v: { count: string }) => `${v.count} stars`,
				onlyPt: "this post is only available in portuguese.",
				noReadme: "this repository has no README yet.",
			},
			meta: {
				title: "Cauã Diorio · front-end developer",
				description: "Front-end developer. Interface, interaction and the details that make a product good to use.",
			},
			role: "front-end developer",
			bio: "i take care of the part people see and use: interface, interaction and the details that make a product good to use. today i work on loopvet, software for veterinary clinics, and domus, a CMS that grew into a content platform.",
			contributions: {
				count: (v: { count: string }) => `${v.count} contributions in the last year on`,
				fallback: "contributions in the last year on",
				less: "less",
				more: "more",
				day: (v: { count: string; date: string }) => `${v.count} contributions on ${v.date}`,
			},
			projects: {
				title: "projects i've worked on",
				loopvet: "management software for veterinary clinics: scheduling, medical records and billing.",
				domus: "a CMS that grew into a content marketing platform: articles, API and campaign links with analytics.",
				converter: "converters that take messy data from other systems and deliver it clean to the database.",
			},
			repos: {
				title: "featured on github",
				all: "see all →",
				stars: (v: { count: string }) => `${v.count} stars`,
			},
			writing: {
				title: "writing",
				all: "see all →",
			},
			notFound: {
				path: "page-that-doesnt-exist",
				error: "cd: no such file or directory",
				title: "this page doesn't exist.",
				body: "the link may be broken or the page moved. type cd .. or head back with the link below.",
				home: "back to the start",
			},
			experience: {
				title: "experience",
				current: "current",
				role: "front-end developer",
			},
		},
		components: {
			"site-shell": {
				tagline: "jaú, sp · brazil",
				nav: {
					label: "Sections and links",
					blog: "blog",
					experience: "experience",
					projects: "projects",
					email: "email",
					cv: "CV",
				},
				theme: {
					toLight: "Switch to light theme",
					toDark: "Switch to dark theme",
				},
				language: {
					label: "Language",
				},
				footer: {
					made: "made by cauã.",
					hint: "psst: type",
				},
			},
		},
	},
} as const;

export type Locale = keyof typeof translations;

/** Runtime config for `better-intl/runtime`, baked into the helpers below. */
export const intlConfig = {
	"defaultLocale": "pt",
	"locales": [
		"pt",
		"en"
	],
	"storage": {
		"type": "cookie",
		"key": "locale"
	}
} as const;

// Helpers bound to `translations` + `intlConfig` once. Import `t` anywhere
// (sync on both client and server); call `setLocale()` once per request in the
// root layout; `getLocale()` returns the active locale string; call
// `updateLocale(locale)` to persist a new preference.
const i18n = createI18n(translations, intlConfig);
export const { t, setLocale, getLocale, updateLocale } = i18n;
