export default {
  nav: {
    label: { pt: "Navegação", en: "Navigation" },
    home: { pt: "início", en: "home" },
    blog: { pt: "blog", en: "blog" },
    lab: { pt: "lab", en: "lab" },
    experience: { pt: "experiência", en: "experience" },
    projects: { pt: "projetos", en: "projects" },
    email: { pt: "e-mail", en: "email" },
    cv: { pt: "CV", en: "CV" },
  },
  theme: {
    toLight: { pt: "Mudar pro tema claro", en: "Switch to light theme" },
    toDark: { pt: "Mudar pro tema escuro", en: "Switch to dark theme" },
  },
  language: {
    label: { pt: "Idioma", en: "Language" },
  },
  palette: {
    open: { pt: "Abrir busca e comandos", en: "Open search and commands" },
    title: { pt: "busca e comandos", en: "search and commands" },
    input: { pt: "Buscar páginas, posts e ações", en: "Search pages, posts and actions" },
    placeholder: { pt: "buscar ou digitar um comando…", en: "search or type a command…" },
    empty: { pt: "nada por aqui.", en: "nothing here." },
    close: { pt: "Fechar", en: "Close" },
    navigate: { pt: "navegar", en: "navigate" },
    select: { pt: "abrir", en: "open" },
    dismiss: { pt: "fechar", en: "close" },
    pages: { pt: "páginas", en: "pages" },
    posts: { pt: "posts", en: "posts" },
    actions: { pt: "ações", en: "actions" },
    home: { pt: "início", en: "home" },
    projects: { pt: "projetos", en: "projects" },
    lab: { pt: "lab", en: "lab" },
    blog: { pt: "blog", en: "blog" },
    cv: { pt: "CV", en: "CV" },
    freela: { pt: "trabalhe comigo", en: "work with me" },
    agora: { pt: "agora", en: "now" },
    log: { pt: "log do site", en: "site log" },
    theme: { pt: "trocar tema", en: "switch theme" },
    themeWords: { pt: "claro escuro dark light theme", en: "light dark tema claro escuro" },
    language: { pt: "trocar idioma pra english", en: "switch language to português" },
    languageWords: { pt: "idioma language en inglês", en: "language idioma pt português" },
    copyLink: { pt: "copiar link da página", en: "copy page link" },
    copied: { pt: "link copiado", en: "link copied" },
    github: { pt: "abrir github", en: "open github" },
  },
  footer: {
    made: { pt: "feito por cauã.", en: "made by cauã." },
    hint: { pt: "psst: digita", en: "psst: type" },
    social: { pt: "Redes", en: "Social" },
  },
  egg: {
    title: { pt: "comandos", en: "commands" },
    intro: { pt: "digita em qualquer lugar da página:", en: "type anywhere on the page:" },
    dismiss: { pt: "Fechar dica", en: "Dismiss hint" },
  },
};
