export default {
  nav: {
    label: { pt: "Navegação", en: "Navigation" },
    home: { pt: "início", en: "home" },
    blog: { pt: "blog", en: "blog" },
    lab: { pt: "lab", en: "lab" },
    experience: { pt: "experiência", en: "experience" },
    projects: { pt: "projetos", en: "projects" },
    email: { pt: "e-mail", en: "email" },
    cv: { pt: "CV", en: "CV" },
  },
  theme: {
    toLight: { pt: "Mudar pro tema claro", en: "Switch to light theme" },
    toDark: { pt: "Mudar pro tema escuro", en: "Switch to dark theme" },
  },
  language: {
    label: { pt: "Idioma", en: "Language" },
  },
  palette: {
    open: { pt: "Abrir busca e comandos", en: "Open search and commands" },
    title: { pt: "busca e comandos", en: "search and commands" },
    input: { pt: "Buscar páginas, posts e ações", en: "Search pages, posts and actions" },
    placeholder: { pt: "buscar ou digitar um comando…", en: "search or type a command…" },
    empty: { pt: "nada por aqui.", en: "nothing here." },
    close: { pt: "Fechar", en: "Close" },
    navigate: { pt: "navegar", en: "navigate" },
    select: { pt: "abrir", en: "open" },
    dismiss: { pt: "fechar", en: "close" },
    pages: { pt: "páginas", en: "pages" },
    posts: { pt: "posts", en: "posts" },
    actions: { pt: "ações", en: "actions" },
    home: { pt: "início", en: "home" },
    projects: { pt: "projetos", en: "projects" },
    lab: { pt: "lab", en: "lab" },
    blog: { pt: "blog", en: "blog" },
    cv: { pt: "CV", en: "CV" },
    freela: { pt: "trabalhe comigo", en: "work with me" },
    agora: { pt: "agora", en: "now" },
    log: { pt: "log do site", en: "site log" },
    theme: { pt: "trocar tema", en: "switch theme" },
    themeWords: { pt: "claro escuro dark light theme", en: "light dark tema claro escuro" },
    language: { pt: "trocar idioma pra english", en: "switch language to português" },
    languageWords: { pt: "idioma language en inglês", en: "language idioma pt português" },
    copyLink: { pt: "copiar link da página", en: "copy page link" },
    copied: { pt: "link copiado", en: "link copied" },
    github: { pt: "abrir github", en: "open github" },
    terminal: { pt: "abrir terminal", en: "open terminal" },
    terminalWords: { pt: "terminal shell console comando cmd", en: "terminal shell console command cmd" },
  },
  footer: {
    made: { pt: "feito por cauã.", en: "made by cauã." },
    hint: { pt: "psst: digita", en: "psst: type" },
    social: { pt: "Redes", en: "Social" },
  },
  egg: {
    title: { pt: "comandos", en: "commands" },
    intro: { pt: "digita em qualquer lugar da página:", en: "type anywhere on the page:" },
    dismiss: { pt: "Fechar dica", en: "Dismiss hint" },
    terminal: { pt: "ou abre o terminal:", en: "or open the terminal:" },
  },
  // Terminal global (Ctrl+J / Ctrl+`). Voz minúscula e curta.
  terminal: {
    title: { pt: "terminal", en: "terminal" },
    close: { pt: "Fechar terminal", en: "Close terminal" },
    label: { pt: "Comando", en: "Command" },
    intro: { pt: "digita help pra ver os comandos.", en: "type help to see the commands." },
    help: {
      pt: [
        "help          lista os comandos",
        "ls            lista seções e projetos",
        "cd <lugar>    navega: cd .., cd lab",
        "pwd           onde você tá",
        "open <proj>   abre o site ou o repo",
        "theme [x]     troca o tema: light | dark",
        "lang [x]      troca o idioma: pt | en",
        "whoami        quem tá por aqui",
        "clear         limpa a tela (ctrl+l)",
        "tab completa, ↑ ↓ histórico, esc fecha.",
      ].join("\n"),
      en: [
        "help          list the commands",
        "ls            list sections and projects",
        "cd <place>    navigate: cd .., cd lab",
        "pwd           where you are",
        "open <proj>   open the site or repo",
        "theme [x]     switch theme: light | dark",
        "lang [x]      switch language: pt | en",
        "whoami        who's around",
        "clear         clear the screen (ctrl+l)",
        "tab completes, ↑ ↓ history, esc closes.",
      ].join("\n"),
    },
    notFound: { pt: "comando não encontrado: {cmd}", en: "command not found: {cmd}" },
    noDir: { pt: "cd: {dir}: lugar inexistente", en: "cd: {dir}: no such place" },
    noProject: { pt: "open: {name}: projeto inexistente", en: "open: {name}: no such project" },
    usage: { pt: "uso: {use}", en: "usage: {use}" },
    opening: { pt: "abrindo {url}", en: "opening {url}" },
  },
};
